name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-xcframeworks:
    name: Build XCFrameworks
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v2
      - name: Archive
        run: sh ./scripts/archive.sh

